# Generated by Django 5.1.1 on 2024-10-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subject_teacher_alter_subject_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(choices=[('first_term', 'first_term'), ('quaterly', 'quaterly'), ('second_term', 'second_term'), ('half_yearly', 'half_yearly'), ('third_term', 'third_term'), ('finals', 'finals')], max_length=20),
        ),
    ]
