# Generated by Django 5.1.1 on 2024-10-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_exam_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='Exam_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
