# Generated by Django 5.1.1 on 2024-10-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_marks_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
    ]
